name: scan-webgoat

on:
  push:
    branches:
      - '*'


#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'dummy'
#        required: true
#        default: 'dummy'

jobs:
    scan:
      runs-on: ubuntu-latest

      steps:
        - name: scan-webgoat
          uses: ./.github/workflows/scan-pmd.yml

        - name: upload results
          uses: actions/upload-artifact@v4
          with:
            name: results
            path: results.xml

#        - name: fail job
#          run: |
#            if [[ $(wc -l <results.xml) -ge 10 ]]
#            then
#              exit -1
#            fi
