name: setup-maven

on:
  push:
    branches:
      - '*'

#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Define env name'
#        required: true
#        default: 'prod'

jobs:
    scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.1.1

        - id: setup-java
          name: Set up JDK
          uses: actions/setup-java@v4.0.0
          with:
            distribution: temurin
            java-version: 17
            cache: maven

        - name: wget
          run: wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc4/pmd-dist-7.0.0-rc4-bin.zip

        - name: unzip
          run: unzip pmd-dist-7.0.0-rc4-bin.zip

        - name: pmd
          run: pmd-bin-7.0.0-rc4/bin/pmd check -d /usr/src -R rulesets/java/quickstart.xml -f text -r result.txt -d src
#    upload:
#      steps:
        - name: Archive code coverage results
          uses: actions/upload-artifact@v3
          with:
            name: results
            path: results.txt
